name: Sample Workflow

on: [ workflow_dispatch, push ]


jobs:
  amd_job:
    name: Amd Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Soruce Code Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          uname -a
          docker build -t test:latest .
          docker inspect test:latest |grep Arch
          docker run -t test:latest
  power_job:
    name: Power Image Build
    runs-on: ubuntu-latest-ppc64le
    steps:
      - name: Soruce Code Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          uname -a
          docker build -t test:latest .
          docker inspect test:latest |grep Arch
          docker run -t test:latest
          
